format = """
$username\
$hostname\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$package\
$python\
$terraform\
$env_var\
$custom\
$line_break\
$jobs\
$character"""

add_newline = false
command_timeout = 2000
scan_timeout = 2000

[battery]
disabled = true

[cmd_duration]
min_time_to_notify = 60_000
show_notifications = true

[directory]
truncate_to_repo = false
truncation_length = 0

[git_branch]
format = "[$symbol$branch]($style)"

[git_state]
format = '\(:[$state( $progress_current/$progress_total)]($style)\)'

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[hostname]
format = '[$hostname]($style) '
ssh_only = true
trim_at = '.'

[python]
detect_extensions = ['py']
detect_files = []
detect_folders = []
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
python_binary = ['python3']

[username]
format = '[$user]($style)@'
show_always = false
style_root = 'bold red'
